# Rustfmt configuration for Mark project (stable-compatible)

# Code style
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Misc formatting
remove_nested_parens = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true

# Chain formatting
chain_width = 60
single_line_if_else_max_width = 50

# Edition
edition = "2021"

# Match formatting
match_block_trailing_comma = false

# Function parameters layout  
fn_params_layout = "Tall"